# Welcome to Jekyll!

plugins:
  - jekyll-feed
  #- jekyll-remote-theme
  
theme: jekyll-agency
#remote_theme: raviriley/agency-jekyll-theme

url    : "http://BackToBitsStudio.github.io"
baseurl: "/"

title      : Back to Bits
email      : BackToBitsStudio@gmail.com
description: Back to Bits, an indie development studio.
author     : marmaestro
logo:
  path: assets/logo/banner-text.png
  height: 60

locale: "en"

#analytics:
#  google: #Google Analytics tracking code here

collections:
  portfolio: 

markdown: kramdown

sass:
  quiet_deps: true
  silence_deprecations: [import]

formspree_id: "f/xeovqzvn"
