# Welcome to Jekyll!

theme: jekyll-agency
plugins:
  - jekyll-feed

#url    : "" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: "" # the subpath of your site, e.g. /blog

title      : Back to Bits
email      : BackToBitsStudio@gmail.com
description: 
author     : marmaestro
logo:
  path: assets/logo/banner-text.png
  height: 60

locale: "es"

#analytics:
#  google: #Google Analytics tracking code here

collections:
  portfolio: 

markdown: kramdown

sass:
  quiet_deps: true
  silence_deprecations: [import]

# Uncomment following line to use Formspree form ID based URL instead of email based URL
formspree_id: "f/xeovqzvn"
